---
name: backend-docker

on:
  push:
    branches: [ master ]
    paths:
      - backend/**
      - .github/workflows/backend-docker.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Echo context
        run: |
          echo "Owner=${{ github.repository_owner }}"
          echo "Ref=${{ github.ref }}"
